version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    pull-request-branch-name: "dependabot-auto-merge"
    # Configuración de auto-merge
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    automerged_updates:
      - match:
          update_type: "semver-minor"
      - match:
          update_type: "semver-patch"
