version: 2
updates:
  - package-ecosystem: "npm" # Especifica el ecosistema, en este caso npm para Node.js
    directory: "../" # Directorio donde se encuentra el archivo package.json, generalmente en la raíz
    schedule:
      interval: "daily" # Frecuencia de actualización: daily (diario), weekly (semanal), monthly (mensual)
    commit-message:
      prefix: "deps" # Prefijo para los mensajes de commit de Dependabot
    open-pull-requests-limit: 5 # Límite de PRs abiertos al mismo tiempo por Dependabot
