version: 2
updates:
  - package-ecosystem: "npm" # npm para manejar dependencias de Node.js
    directory: "/" # La raíz del repositorio, donde se encuentra package.json
    schedule:
      interval: "daily" # Frecuencia de actualización diaria
    commit-message:
      prefix: "deps" # Prefijo de los mensajes de commit
    open-pull-requests-limit: 10 # Límite de PRs abiertos al mismo tiempo por Dependabot

