version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
    reviewers:
      - "AGuekdjian"
