name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'AGuekdjian'
    steps:
      - name: Check if PR is ready for auto-merge
        run: |
          if [ "$(jq -r '.pull_request.head.repo.full_name' $GITHUB_EVENT_PATH)" == "$GITHUB_REPOSITORY" ] && \
             [ "$(jq -r '.pull_request.base.ref' $GITHUB_EVENT_PATH)" == "main" ]; then
            echo "PR is ready for auto-merge";
          else
            echo "Not ready for auto-merge" && exit 1;
          fi

      - name: Auto-merge PR
        env:
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}  # Asegúrate de que este secreto esté configurado correctamente
        run: |
          gh pr merge -R "AGuekdjian/Portfolio-v2" --squash --auto "${{ github.event.pull_request.number }}"

